package inspection

// ChecklistCA returns the California LIC-9099 walk-through the analyst would
// see on a Community Care Licensing pre-licensing / annual review visit.
// Items follow the nine LIC-9099 domains in their on-form order. Citations
// are Title 22, Division 12, Chapter 1 ("General Requirements for Child Care
// Centers").
func ChecklistCA() []Item {
	return []Item{
		// --- 1. Personnel ---
		{ID: "ca.personnel.director_qualifications", Domain: "Personnel",
			Question: "Does the director meet the qualifications in Title 22 (at least 15 core ECE units + 4 units admin + experience)?",
			Reference: "22 CCR §101315", FormRef: "LIC 9099 Item 1.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.personnel.teacher_qualifications", Domain: "Personnel",
			Question: "Do all teachers have at least 12 ECE core units or equivalent permit on file?",
			Reference: "22 CCR §101216.1", FormRef: "LIC 9099 Item 1.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.personnel.criminal_record_clearance", Domain: "Personnel",
			Question: "Does every employee have a current LIC-508 criminal record clearance or exemption on file before first contact with children?",
			Reference: "Health & Safety §1596.871", FormRef: "LIC 9099 Item 1.3",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.personnel.child_abuse_index", Domain: "Personnel",
			Question: "Has a Child Abuse Central Index check (CACI, LIC-198B) been completed for every employee?",
			Reference: "Health & Safety §1596.877", FormRef: "LIC 9099 Item 1.4",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.personnel.tb_test", Domain: "Personnel",
			Question: "Does each staff member have a TB test (LIC-503) dated within the last year of hire?",
			Reference: "22 CCR §101216", FormRef: "LIC 9099 Item 1.5",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.personnel.health_screening", Domain: "Personnel",
			Question: "Is a current health screening report (LIC-503) on file for each employee with direct child contact?",
			Reference: "22 CCR §101216", FormRef: "LIC 9099 Item 1.6",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.personnel.mandated_reporter_training", Domain: "Personnel",
			Question: "Has every employee completed mandated-reporter training within 6 weeks of hire?",
			Reference: "Penal Code §11165.7", FormRef: "LIC 9099 Item 1.7",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.personnel.staff_child_ratio", Domain: "Personnel",
			Question: "Are staff-to-child ratios met in every classroom right now (1:4 infants, 1:12 preschool)?",
			Reference: "22 CCR §101216.3", FormRef: "LIC 9099 Item 1.8",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},

		// --- 2. Administration ---
		{ID: "ca.admin.license_posted", Domain: "Administration",
			Question: "Is the facility license (LIC-203) posted in a conspicuous location where parents enter?",
			Reference: "22 CCR §101237", FormRef: "LIC 9099 Item 2.1",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "ca.admin.admissions_agreement", Domain: "Administration",
			Question: "Is a signed LIC-9166 admissions agreement on file for every enrolled child?",
			Reference: "22 CCR §101218", FormRef: "LIC 9099 Item 2.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.admin.personal_rights_posted", Domain: "Administration",
			Question: "Is the LIC-9119 Personal Rights for Child Day Care form posted where parents and staff can see it?",
			Reference: "22 CCR §101223", FormRef: "LIC 9099 Item 2.3",
			EvidenceKind: EvidencePhoto, Severity: SeverityMinor},
		{ID: "ca.admin.parent_complaint_posted", Domain: "Administration",
			Question: "Is the Parents' Rights (PUB 393) poster displayed with the CCLD complaint phone number?",
			Reference: "Health & Safety §1596.857", FormRef: "LIC 9099 Item 2.4",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},

		// --- 3. Physical Plant ---
		{ID: "ca.physical.indoor_sqft", Domain: "Physical Plant",
			Question: "Does the facility provide at least 35 sq ft of indoor activity space per child?",
			Reference: "22 CCR §101227", FormRef: "LIC 9099 Item 3.1",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "ca.physical.outdoor_sqft", Domain: "Physical Plant",
			Question: "Does the facility provide at least 75 sq ft of outdoor activity space per child (or a DCC-approved alternate)?",
			Reference: "22 CCR §101228", FormRef: "LIC 9099 Item 3.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "ca.physical.fire_clearance", Domain: "Physical Plant",
			Question: "Is a current LIC-9148 fire-clearance letter on file and posted?",
			Reference: "22 CCR §101171", FormRef: "LIC 9099 Item 3.3",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.physical.hazards_secured", Domain: "Physical Plant",
			Question: "Are all cleaning supplies, medications, and chemicals stored in locked cabinets out of children's reach?",
			Reference: "22 CCR §101238.2", FormRef: "LIC 9099 Item 3.4",
			EvidenceKind: EvidencePhoto, Severity: SeverityCritical},

		// --- 4. Health & Safety ---
		{ID: "ca.health.disaster_plan", Domain: "Health & Safety",
			Question: "Is a written disaster plan (earthquake, fire, lockdown) posted, dated, and reviewed within the last year?",
			Reference: "22 CCR §101174", FormRef: "LIC 9099 Item 4.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.health.drills_logged", Domain: "Health & Safety",
			Question: "Have fire and earthquake drills been conducted and logged in each of the last 6 months?",
			Reference: "22 CCR §101174", FormRef: "LIC 9099 Item 4.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.health.first_aid_kit", Domain: "Health & Safety",
			Question: "Is a stocked first-aid kit accessible to staff but not to children in every occupied room?",
			Reference: "22 CCR §101226", FormRef: "LIC 9099 Item 4.3",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "ca.health.cpr_on_site", Domain: "Health & Safety",
			Question: "Is at least one staff member with current CPR + Pediatric First Aid certification on-site during all hours children are present?",
			Reference: "Health & Safety §1596.866", FormRef: "LIC 9099 Item 4.4",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.health.medication_authorization", Domain: "Health & Safety",
			Question: "Is a signed LIC-9221 medication authorization on file for every prescription currently administered?",
			Reference: "22 CCR §101226.1", FormRef: "LIC 9099 Item 4.5",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},

		// --- 5. Child Records ---
		{ID: "ca.records.identification", Domain: "Child Records",
			Question: "Does every enrolled child have a completed LIC-613A identification and emergency information form?",
			Reference: "22 CCR §101221", FormRef: "LIC 9099 Item 5.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.records.physicians_report", Domain: "Child Records",
			Question: "Is a completed LIC-701 Physician's Report on file for each child within 30 days of enrollment?",
			Reference: "22 CCR §101220.1", FormRef: "LIC 9099 Item 5.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.records.immunizations", Domain: "Child Records",
			Question: "Does every enrolled child have a current California immunization record (blue card) that meets SB-277?",
			Reference: "Health & Safety §120335", FormRef: "LIC 9099 Item 5.3",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},

		// --- 6. Program ---
		{ID: "ca.program.daily_schedule_posted", Domain: "Program",
			Question: "Is the daily activity schedule posted in each classroom and age-appropriate?",
			Reference: "22 CCR §101229", FormRef: "LIC 9099 Item 6.1",
			EvidenceKind: EvidencePhoto, Severity: SeverityMinor},
		{ID: "ca.program.developmental_activities", Domain: "Program",
			Question: "Do classroom activities include a balance of indoor/outdoor, quiet/active, and individual/group play?",
			Reference: "22 CCR §101229.1", FormRef: "LIC 9099 Item 6.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMinor},

		// --- 7. Food Service ---
		{ID: "ca.food.menu_posted", Domain: "Food Service",
			Question: "Is a weekly menu posted where parents can see it, with substitutions recorded?",
			Reference: "22 CCR §101227", FormRef: "LIC 9099 Item 7.1",
			EvidenceKind: EvidencePhoto, Severity: SeverityMinor},
		{ID: "ca.food.handler_permit", Domain: "Food Service",
			Question: "Does the person preparing food have a current county food handler card?",
			Reference: "CA Health & Safety §113947", FormRef: "LIC 9099 Item 7.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "ca.food.formula_labeled", Domain: "Food Service",
			Question: "Are infant bottles and formula containers labeled with the child's name and date?",
			Reference: "22 CCR §101227", FormRef: "LIC 9099 Item 7.3",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMajor},

		// --- 8. Transportation ---
		{ID: "ca.transport.driver_license", Domain: "Transportation",
			Question: "Does every driver carry a current license appropriate for the vehicle and passenger count?",
			Reference: "22 CCR §101216.2", FormRef: "LIC 9099 Item 8.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "ca.transport.signed_authorization", Domain: "Transportation",
			Question: "Is a written LIC-627 parental transportation authorization on file for every child transported?",
			Reference: "22 CCR §101227.2", FormRef: "LIC 9099 Item 8.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},

		// --- 9. Night Care ---
		{ID: "ca.night.sleeping_arrangements", Domain: "Night Care",
			Question: "If night care is provided, does each child have an individual bed with clean linens changed weekly?",
			Reference: "22 CCR §101230", FormRef: "LIC 9099 Item 9.1",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMajor},
		{ID: "ca.night.awake_supervision", Domain: "Night Care",
			Question: "If night care is provided, is an awake, trained staff member supervising at all times?",
			Reference: "22 CCR §101216.3", FormRef: "LIC 9099 Item 9.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
	}
}
