package inspection

// ChecklistFL mirrors Florida CF-FSP 5316 Child Care Standards Classification
// Summary: 32 inspection categories in the walk-through order DCF field
// inspectors use. Citations reference F.A.C. 65C-22 and the Child Care Facility
// Handbook (CFOP 170-20). Severity maps to Florida's Class 1/2/3 violation
// scheme (Class 1 = Critical, Class 2 = Major, Class 3 = Minor).
func ChecklistFL() []Item {
	return []Item{
		{ID: "fl.01.ratios", Domain: "Supervision",
			Question: "Are staff-to-child ratios and maximum group sizes being met at this moment?",
			Reference: "F.A.C. 65C-22.001(4)", FormRef: "CF-FSP 5316 #01",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "fl.02.direct_supervision", Domain: "Supervision",
			Question: "Is every child in direct line-of-sight supervision during all activities including naps and bathroom breaks?",
			Reference: "F.A.C. 65C-22.001(5)", FormRef: "CF-FSP 5316 #02",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "fl.03.child_discipline", Domain: "Child Discipline",
			Question: "Is the facility's written discipline policy consistent with 402.305(12), F.S. and provided to every parent?",
			Reference: "F.S. §402.305(12)", FormRef: "CF-FSP 5316 #03",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.04.minimum_standards_posted", Domain: "Administration",
			Question: "Are the Florida Child Care Facility Minimum Standards posted where parents can read them?",
			Reference: "F.A.C. 65C-22.003(2)", FormRef: "CF-FSP 5316 #04",
			EvidenceKind: EvidencePhoto, Severity: SeverityMinor},
		{ID: "fl.05.license_posted", Domain: "Administration",
			Question: "Is the current DCF license posted in a conspicuous location near the main entrance?",
			Reference: "F.A.C. 65C-22.001(7)", FormRef: "CF-FSP 5316 #05",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "fl.06.planned_activities", Domain: "Program",
			Question: "Is a daily planned activity schedule posted in every classroom including quiet/active and indoor/outdoor components?",
			Reference: "F.A.C. 65C-22.001(6)", FormRef: "CF-FSP 5316 #06",
			EvidenceKind: EvidencePhoto, Severity: SeverityMinor},
		{ID: "fl.07.staff_training", Domain: "Staff Training",
			Question: "Has every staff member completed the 45-hour DCF introductory child care training within 12 months of hire?",
			Reference: "F.A.C. 65C-22.003(4)", FormRef: "CF-FSP 5316 #07",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.08.in_service_training", Domain: "Staff Training",
			Question: "Does every staff member have the required 10 hours of annual in-service training documented?",
			Reference: "F.A.C. 65C-22.003(7)", FormRef: "CF-FSP 5316 #08",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.09.cpr_first_aid", Domain: "Staff Training",
			Question: "Is at least one staff member with current pediatric CPR + First Aid on the premises during all hours of operation?",
			Reference: "F.A.C. 65C-22.003(5)", FormRef: "CF-FSP 5316 #09",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.10.director_credential", Domain: "Staff Training",
			Question: "Does the director hold a current Florida Director Credential (Level I or II)?",
			Reference: "F.A.C. 65C-22.003(8)", FormRef: "CF-FSP 5316 #10",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.11.background_screening", Domain: "Personnel",
			Question: "Does every owner, operator, employee, and volunteer have current Level 2 background screening results on file?",
			Reference: "F.S. §435.04", FormRef: "CF-FSP 5316 #11",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.12.personnel_records", Domain: "Personnel",
			Question: "Does every employee have a completed CF-FSP 5337 personnel record on file including attestation of good moral character?",
			Reference: "F.A.C. 65C-22.006(4)", FormRef: "CF-FSP 5316 #12",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.13.child_enrollment_records", Domain: "Child Records",
			Question: "Is a completed CF-FSP 5219 enrollment form on file for every child at admission?",
			Reference: "F.A.C. 65C-22.006(2)", FormRef: "CF-FSP 5316 #13",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.14.immunization_records", Domain: "Child Records",
			Question: "Does every enrolled child have a current DH Form 680 (immunization) or 681 (exemption) on file?",
			Reference: "F.S. §1003.22", FormRef: "CF-FSP 5316 #14",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.15.student_health_exam", Domain: "Child Records",
			Question: "Does every enrolled child have a current DH Form 3040 student health examination on file?",
			Reference: "F.A.C. 65C-22.006(2)(c)", FormRef: "CF-FSP 5316 #15",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.16.food_nutrition", Domain: "Food & Nutrition",
			Question: "Does the weekly menu meet USDA CACFP meal pattern requirements and is it posted for parents?",
			Reference: "F.A.C. 65C-22.005(1)", FormRef: "CF-FSP 5316 #16",
			EvidenceKind: EvidenceDocument, Severity: SeverityMinor},
		{ID: "fl.17.food_safety", Domain: "Food & Nutrition",
			Question: "Is food stored, prepared, and served in a way that prevents contamination (temperatures, hand-washing, covered storage)?",
			Reference: "F.A.C. 65C-22.005(3)", FormRef: "CF-FSP 5316 #17",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "fl.18.napping_equipment", Domain: "Physical Environment",
			Question: "Does every child have individual, sanitary napping equipment spaced at least 18 inches apart?",
			Reference: "F.A.C. 65C-22.002(5)", FormRef: "CF-FSP 5316 #18",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "fl.19.indoor_sqft", Domain: "Physical Environment",
			Question: "Does the facility provide at least 35 usable sq ft of indoor floor space per child?",
			Reference: "F.A.C. 65C-22.002(4)", FormRef: "CF-FSP 5316 #19",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "fl.20.outdoor_sqft", Domain: "Physical Environment",
			Question: "Does the outdoor play area provide at least 45 sq ft per child, shaded, fenced, and free of hazards?",
			Reference: "F.A.C. 65C-22.002(7)", FormRef: "CF-FSP 5316 #20",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "fl.21.bathroom_equipment", Domain: "Physical Environment",
			Question: "Is there at least one toilet + sink for every 15 children, and diapering surfaces sanitized between children?",
			Reference: "F.A.C. 65C-22.002(8)", FormRef: "CF-FSP 5316 #21",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "fl.22.hygiene_practices", Domain: "Physical Environment",
			Question: "Are hand-washing, diapering, and toileting routines carried out consistently with posted procedures?",
			Reference: "F.A.C. 65C-22.002(9)", FormRef: "CF-FSP 5316 #22",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMajor},
		{ID: "fl.23.health_sanitation", Domain: "Health & Sanitation",
			Question: "Is the facility clean, free from rodents/insects, and are cleaning chemicals locked away from children?",
			Reference: "F.A.C. 65C-22.002(1)", FormRef: "CF-FSP 5316 #23",
			EvidenceKind: EvidencePhoto, Severity: SeverityCritical},
		{ID: "fl.24.hazardous_materials", Domain: "Health & Sanitation",
			Question: "Are all medications, cleaning supplies, and hazardous materials stored in locked cabinets with labels intact?",
			Reference: "F.A.C. 65C-22.002(1)(d)", FormRef: "CF-FSP 5316 #24",
			EvidenceKind: EvidencePhoto, Severity: SeverityCritical},
		{ID: "fl.25.fire_safety", Domain: "Fire Safety",
			Question: "Is the annual fire inspection current, posted, and free of open violations?",
			Reference: "F.A.C. 65C-22.002(3)", FormRef: "CF-FSP 5316 #25",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.26.emergency_plan", Domain: "Emergency Preparedness",
			Question: "Is a written emergency preparedness plan (fire, tornado, evacuation) posted and reviewed with staff at least annually?",
			Reference: "F.A.C. 65C-22.002(2)", FormRef: "CF-FSP 5316 #26",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.27.emergency_drills", Domain: "Emergency Preparedness",
			Question: "Are fire drills conducted monthly and severe-weather drills conducted at least twice per year with logs on file?",
			Reference: "F.A.C. 65C-22.002(2)(c)", FormRef: "CF-FSP 5316 #27",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.28.transportation", Domain: "Transportation",
			Question: "Are children transported with licensed drivers, appropriate safety restraints, and vehicle logs (CF-FSP 5239) maintained?",
			Reference: "F.S. §402.305(10)", FormRef: "CF-FSP 5316 #28",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.29.transportation_face_to_name", Domain: "Transportation",
			Question: "Is a face-to-name count log kept for every child loaded and unloaded from every vehicle?",
			Reference: "F.S. §402.305(10)(c)", FormRef: "CF-FSP 5316 #29",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "fl.30.access_parents", Domain: "Parent Communication",
			Question: "Do parents have unrestricted access to their child and the classroom during hours of operation?",
			Reference: "F.A.C. 65C-22.001(8)", FormRef: "CF-FSP 5316 #30",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMinor},
		{ID: "fl.31.incident_reports", Domain: "Reporting",
			Question: "Are accident/incident reports (CF-FSP 5306) completed within 24 hours and a copy given to the parent?",
			Reference: "F.A.C. 65C-22.004(2)", FormRef: "CF-FSP 5316 #31",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "fl.32.serious_incident_reporting", Domain: "Reporting",
			Question: "Is every serious incident reported to DCF within the 24-hour window (death, hospitalization, abuse allegation)?",
			Reference: "F.S. §402.301", FormRef: "CF-FSP 5316 #32",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
	}
}
