package inspection

// ChecklistTX mirrors Texas HHSC Form 2936 Annual Licensing Inspection plus
// the records-evaluation trio (7259 Personnel, 7260 Children's, 7261 Center).
// Citations refer to 26 TAC Chapter 746 ("Minimum Standards for Child-Care
// Centers") unless noted.
func ChecklistTX() []Item {
	return []Item{
		// --- Administration (Form 2936 + Form 7261 Center records) ---
		{ID: "tx.admin.license_posted", Domain: "Administration",
			Question: "Is the current Texas HHSC license posted in a conspicuous location near the main entrance?",
			Reference: "26 TAC §746.305", FormRef: "Form 2936 §A.1 / Form 7261",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "tx.admin.operational_policies", Domain: "Administration",
			Question: "Are written operational policies (including discipline and guidance) available to every parent at enrollment?",
			Reference: "26 TAC §746.501", FormRef: "Form 2936 §A.2",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.admin.liability_insurance_notice", Domain: "Administration",
			Question: "Is the current Form 2941 liability-insurance status notice posted for parents, or parents notified in writing?",
			Reference: "Human Resources Code §42.049", FormRef: "Form 2941",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.admin.emergency_numbers_posted", Domain: "Administration",
			Question: "Are emergency numbers (911, Poison Control, Licensing Region office) posted by every phone?",
			Reference: "26 TAC §746.503", FormRef: "Form 2936 §A.3",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},

		// --- Personnel Records (Form 7259) ---
		{ID: "tx.personnel.director_qualifications", Domain: "Personnel Records",
			Question: "Does the director meet Chapter 746 qualifications (child-development credential or 60 college hours)?",
			Reference: "26 TAC §746.1015", FormRef: "Form 7259 Item 1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.personnel.background_check", Domain: "Personnel Records",
			Question: "Does every caregiver and employee have a current Form 2971 fingerprint background check on file before first contact with children?",
			Reference: "26 TAC §745.615", FormRef: "Form 7259 Item 2",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.personnel.preservice_training", Domain: "Personnel Records",
			Question: "Has every caregiver completed the 8 hours of pre-service orientation before counting in ratio?",
			Reference: "26 TAC §746.1305", FormRef: "Form 7259 Item 3",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.personnel.annual_training_hours", Domain: "Personnel Records",
			Question: "Does each caregiver have the required 24 hours of annual training documented?",
			Reference: "26 TAC §746.1309", FormRef: "Form 7259 Item 4",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.personnel.cpr_first_aid", Domain: "Personnel Records",
			Question: "Is at least one caregiver with current CPR + First Aid on-site at all times, and are all caregivers certified within 90 days of hire?",
			Reference: "26 TAC §746.1315", FormRef: "Form 7259 Item 5",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.personnel.tb_test", Domain: "Personnel Records",
			Question: "Has every employee completed TB screening as required by the local health authority?",
			Reference: "26 TAC §746.3605", FormRef: "Form 7259 Item 6",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},

		// --- Children's Records (Form 7260) ---
		{ID: "tx.children.admission_form", Domain: "Children's Records",
			Question: "Is a completed Form 2935 admission information sheet on file for every enrolled child?",
			Reference: "26 TAC §746.601", FormRef: "Form 7260 Item 1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.children.immunization", Domain: "Children's Records",
			Question: "Is an up-to-date Texas immunization record (or valid exemption affidavit) on file for every child?",
			Reference: "25 TAC §97.63", FormRef: "Form 7260 Item 2",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.children.health_statement", Domain: "Children's Records",
			Question: "Is a current health statement from a licensed health-care provider on file for every child?",
			Reference: "26 TAC §746.603", FormRef: "Form 7260 Item 3",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.children.vision_hearing", Domain: "Children's Records",
			Question: "Do children 4+ have current Texas vision and hearing screening results on file?",
			Reference: "25 TAC §37.23", FormRef: "Form 7260 Item 4",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.children.emergency_contacts", Domain: "Children's Records",
			Question: "Does every child's file list at least two emergency contacts plus authorized pick-up adults?",
			Reference: "26 TAC §746.601", FormRef: "Form 7260 Item 5",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},

		// --- Physical Plant ---
		{ID: "tx.physical.fire_inspection", Domain: "Physical Plant",
			Question: "Is a current Form 1100 annual fire-inspection report on file and posted?",
			Reference: "26 TAC §746.5201", FormRef: "Form 1100",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.physical.health_inspection", Domain: "Physical Plant",
			Question: "Is a current county/city health inspection report on file if meals are prepared on-site?",
			Reference: "26 TAC §746.3301", FormRef: "Form 2936 §C.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.physical.indoor_sqft", Domain: "Physical Plant",
			Question: "Does each classroom provide at least 30 sq ft of usable indoor space per child?",
			Reference: "26 TAC §746.4503", FormRef: "Form 2936 §C.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "tx.physical.outdoor_sqft", Domain: "Physical Plant",
			Question: "Does the outdoor play area provide at least 80 sq ft per child using it at one time?",
			Reference: "26 TAC §746.4507", FormRef: "Form 2936 §C.3",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "tx.physical.hazardous_locked", Domain: "Physical Plant",
			Question: "Are all hazardous items (chemicals, sharp objects, medications) in locked storage out of children's reach?",
			Reference: "26 TAC §746.3401", FormRef: "Form 2936 §C.4",
			EvidenceKind: EvidencePhoto, Severity: SeverityCritical},
		{ID: "tx.physical.water_temp", Domain: "Physical Plant",
			Question: "Is hot-water temperature at every child-accessible tap limited to 100 °F / 38 °C?",
			Reference: "26 TAC §746.4501", FormRef: "Form 2936 §C.5",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMajor},

		// --- Ratios & Group Size ---
		{ID: "tx.ratios.current", Domain: "Ratios & Group Size",
			Question: "Are caregiver-child ratios and group sizes compliant with the age-range table right now in every classroom?",
			Reference: "26 TAC §746.1601", FormRef: "Form 2936 §D.1",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
		{ID: "tx.ratios.napping_supervision", Domain: "Ratios & Group Size",
			Question: "Are infants and toddlers supervised by sight and sound at all times, including during naps?",
			Reference: "26 TAC §746.2103", FormRef: "Form 2936 §D.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},

		// --- Health Practices ---
		{ID: "tx.health.hand_washing", Domain: "Health Practices",
			Question: "Are hand-washing procedures followed by staff and children at required times (before meals, after diapering, etc.)?",
			Reference: "26 TAC §746.3401", FormRef: "Form 2936 §E.1",
			EvidenceKind: EvidenceAttestation, Severity: SeverityMajor},
		{ID: "tx.health.diapering_procedure", Domain: "Health Practices",
			Question: "Is the diaper-changing area separate from food areas, sanitized between children, and a posted procedure followed?",
			Reference: "26 TAC §746.3403", FormRef: "Form 2936 §E.2",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},
		{ID: "tx.health.medication_log", Domain: "Health Practices",
			Question: "Is a medication log with written parental consent maintained for every medication administered?",
			Reference: "26 TAC §746.3603", FormRef: "Form 2936 §E.3",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.health.safe_sleep", Domain: "Health Practices",
			Question: "Are infants placed on their backs to sleep in cribs meeting CPSC standards with no soft bedding?",
			Reference: "26 TAC §746.2427", FormRef: "Form 2936 §E.4",
			EvidenceKind: EvidencePhoto, Severity: SeverityCritical},

		// --- Emergency Preparedness (Forms 7263 / 7262) ---
		{ID: "tx.emergency.plan_posted", Domain: "Emergency Preparedness",
			Question: "Is a current emergency preparedness plan (Form 7263) posted and accessible to every caregiver?",
			Reference: "26 TAC §746.5301", FormRef: "Form 7263",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.emergency.drills_logged", Domain: "Emergency Preparedness",
			Question: "Are fire drills conducted monthly and severe-weather/shelter-in-place drills conducted quarterly with logs on file?",
			Reference: "26 TAC §746.5303", FormRef: "Form 2936 §F.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityMajor},
		{ID: "tx.emergency.evacuation_supplies", Domain: "Emergency Preparedness",
			Question: "Is an emergency go-bag with 72 hours of supplies for children and staff ready to carry?",
			Reference: "26 TAC §746.5305", FormRef: "Form 2936 §F.2",
			EvidenceKind: EvidencePhoto, Severity: SeverityMajor},

		// --- Transportation ---
		{ID: "tx.transport.driver_requirements", Domain: "Transportation",
			Question: "Does every driver hold a valid Texas license of the correct class and is a passenger log maintained?",
			Reference: "26 TAC §746.5501", FormRef: "Form 2936 §G.1",
			EvidenceKind: EvidenceDocument, Severity: SeverityCritical},
		{ID: "tx.transport.child_safety_seats", Domain: "Transportation",
			Question: "Are child safety seats / seat belts used for every child on every trip, appropriate to height/age?",
			Reference: "Tex. Transp. Code §545.412", FormRef: "Form 2936 §G.2",
			EvidenceKind: EvidenceAttestation, Severity: SeverityCritical},
	}
}
