package immunization

// Deterministic CDC child immunization schedule. NOT to be generated by an LLM.
// Source: CDC Advisory Committee on Immunization Practices (ACIP) 2024 schedule.
// States (CA, TX, FL) adopt the CDC schedule verbatim for enrollment purposes;
// state-specific overrides live in the Notes field.

type Status string

const (
	StatusDue      Status = "due"
	StatusOverdue  Status = "overdue"
	StatusUpcoming Status = "upcoming"
	StatusComplete Status = "complete"
)

// Immunization describes one dose requirement at a given age window.
type Immunization struct {
	Vaccine     string `json:"vaccine"`      // DTaP, IPV, MMR, Varicella, HepB, HepA, Hib, PCV13, RV, Influenza
	DoseNumber  int    `json:"dose_number"`  // 1..N
	MinAgeMonth int    `json:"min_age_mo"`
	MaxAgeMonth int    `json:"max_age_mo"`  // 0 means ongoing/annual
	Notes       string `json:"notes,omitempty"`
}

// Required returns the CDC-recommended doses the child SHOULD have received by the given age.
// stateCode reserved for future overrides (e.g. FL varicella rules, CA flu mandates).
func Required(stateCode string, childAgeMonths int) []Immunization {
	var out []Immunization
	for _, i := range fullSchedule {
		if i.MinAgeMonth <= childAgeMonths {
			// Include if currently due or overdue — anything whose min-age has been reached.
			// Annual vaccines (MaxAgeMonth == 0) are always listed once reached.
			out = append(out, i)
		}
	}
	_ = stateCode // reserved
	return out
}

// fullSchedule — each row represents one expected dose.
// Ages are approximated against CDC's standard catch-up tolerance.
var fullSchedule = []Immunization{
	// Hepatitis B: birth, 1-2mo, 6-18mo
	{Vaccine: "HepB", DoseNumber: 1, MinAgeMonth: 0, MaxAgeMonth: 1},
	{Vaccine: "HepB", DoseNumber: 2, MinAgeMonth: 1, MaxAgeMonth: 2},
	{Vaccine: "HepB", DoseNumber: 3, MinAgeMonth: 6, MaxAgeMonth: 18},

	// Rotavirus: 2mo, 4mo, (6mo for RV5)
	{Vaccine: "RV", DoseNumber: 1, MinAgeMonth: 2, MaxAgeMonth: 4, Notes: "Max age for 1st dose 14wk 6d"},
	{Vaccine: "RV", DoseNumber: 2, MinAgeMonth: 4, MaxAgeMonth: 6},

	// DTaP: 2, 4, 6, 15-18mo, 4-6yr
	{Vaccine: "DTaP", DoseNumber: 1, MinAgeMonth: 2, MaxAgeMonth: 3},
	{Vaccine: "DTaP", DoseNumber: 2, MinAgeMonth: 4, MaxAgeMonth: 5},
	{Vaccine: "DTaP", DoseNumber: 3, MinAgeMonth: 6, MaxAgeMonth: 7},
	{Vaccine: "DTaP", DoseNumber: 4, MinAgeMonth: 15, MaxAgeMonth: 18},
	{Vaccine: "DTaP", DoseNumber: 5, MinAgeMonth: 48, MaxAgeMonth: 72},

	// Hib: 2, 4, 6, 12-15mo (third dose product-dependent)
	{Vaccine: "Hib", DoseNumber: 1, MinAgeMonth: 2, MaxAgeMonth: 3},
	{Vaccine: "Hib", DoseNumber: 2, MinAgeMonth: 4, MaxAgeMonth: 5},
	{Vaccine: "Hib", DoseNumber: 3, MinAgeMonth: 6, MaxAgeMonth: 15, Notes: "PRP-T only; PRP-OMP skips dose 3"},
	{Vaccine: "Hib", DoseNumber: 4, MinAgeMonth: 12, MaxAgeMonth: 15},

	// PCV13: 2, 4, 6, 12-15mo
	{Vaccine: "PCV13", DoseNumber: 1, MinAgeMonth: 2, MaxAgeMonth: 3},
	{Vaccine: "PCV13", DoseNumber: 2, MinAgeMonth: 4, MaxAgeMonth: 5},
	{Vaccine: "PCV13", DoseNumber: 3, MinAgeMonth: 6, MaxAgeMonth: 7},
	{Vaccine: "PCV13", DoseNumber: 4, MinAgeMonth: 12, MaxAgeMonth: 15},

	// IPV: 2, 4, 6-18mo, 4-6yr
	{Vaccine: "IPV", DoseNumber: 1, MinAgeMonth: 2, MaxAgeMonth: 3},
	{Vaccine: "IPV", DoseNumber: 2, MinAgeMonth: 4, MaxAgeMonth: 5},
	{Vaccine: "IPV", DoseNumber: 3, MinAgeMonth: 6, MaxAgeMonth: 18},
	{Vaccine: "IPV", DoseNumber: 4, MinAgeMonth: 48, MaxAgeMonth: 72},

	// Influenza: annual starting at 6 months
	{Vaccine: "Influenza", DoseNumber: 1, MinAgeMonth: 6, MaxAgeMonth: 0, Notes: "Annual; 2 doses separated by 4wk for first-time recipients <9yr"},

	// MMR: 12-15mo, 4-6yr
	{Vaccine: "MMR", DoseNumber: 1, MinAgeMonth: 12, MaxAgeMonth: 15},
	{Vaccine: "MMR", DoseNumber: 2, MinAgeMonth: 48, MaxAgeMonth: 72},

	// Varicella: 12-15mo, 4-6yr
	{Vaccine: "Varicella", DoseNumber: 1, MinAgeMonth: 12, MaxAgeMonth: 15},
	{Vaccine: "Varicella", DoseNumber: 2, MinAgeMonth: 48, MaxAgeMonth: 72},

	// Hepatitis A: 12-23mo, 2nd dose >=6mo later
	{Vaccine: "HepA", DoseNumber: 1, MinAgeMonth: 12, MaxAgeMonth: 23},
	{Vaccine: "HepA", DoseNumber: 2, MinAgeMonth: 18, MaxAgeMonth: 29},
}

// AllVaccines returns the unique set of vaccines tracked by this schedule.
func AllVaccines() []string {
	seen := map[string]struct{}{}
	var out []string
	for _, i := range fullSchedule {
		if _, ok := seen[i.Vaccine]; ok {
			continue
		}
		seen[i.Vaccine] = struct{}{}
		out = append(out, i.Vaccine)
	}
	return out
}
